const USER_CONNECTED = 'USER_CONNECTED';
const USER_DISCONNECTED = 'USER_DISCONNECTED';

const NEW_MESSAGE = 'NEW_MESSAGE';
const CREATE_MESSAGE = 'CREATE_MESSAGE';

const NEW_TRADE = 'NEW_TRADE';
const CREATE_TRADE = 'CREATE_TRADE';
const UPDATE_TRADE = 'UPDATE_TRADE';

const JOIN_CHANNEL = 'JOIN_CHANNEL';

const UPDATE_TOPIC_LIST = 'UPDATE_TOPIC_LIST';

const CREATE_TOPIC = 'CREATE_TOPIC';
const ADD_TOPIC_VOTE = 'ADD_TOPIC_VOTE';
const REMOVE_TOPIC_VOTE = 'REMOVE_TOPIC_VOTE';
const UPDATE_USER_LIST = 'UPDATE_USER_LIST';

module.exports = {
    USER_CONNECTED,
    USER_DISCONNECTED,
    NEW_MESSAGE,
    CREATE_MESSAGE,
    NEW_TRADE,
    CREATE_TRADE,
    UPDATE_TRADE,
    JOIN_CHANNEL,
    UPDATE_USER_LIST,
    CREATE_TOPIC,
    ADD_TOPIC_VOTE,
    REMOVE_TOPIC_VOTE,
    UPDATE_TOPIC_LIST
};