const USER_CONNECTED = 'USER_CONNECTED';
const USER_DISCONNECTED = 'USER_DISCONNECTED';
const JOIN_CHANNEL = 'JOIN_CHANNEL';
const UPDATE_USER_LIST = 'UPDATE_USER_LIST';

const NEW_MESSAGE = 'NEW_MESSAGE';
const CREATE_MESSAGE = 'CREATE_MESSAGE';

const UPDATE_CALL_LIST = 'UPDATE_CALL_LIST';
const NEW_CALL = 'NEW_CALL';
const CREATE_CALL = 'CREATE_CALL';
const UPDATE_CALL = 'UPDATE_CALL';
const REMOVE_CALL = 'REMOVE_CALL';

const UPDATE_TOPIC_LIST = 'UPDATE_TOPIC_LIST';
const CREATE_TOPIC = 'CREATE_TOPIC';
const ADD_TOPIC_VOTE = 'ADD_TOPIC_VOTE';
const REMOVE_TOPIC_VOTE = 'REMOVE_TOPIC_VOTE';

const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
const SET_SUBJECT = 'SET_SUBJECT';

const UPDATE_SIGNALED_LIST = 'UPDATE_SIGNALED_LIST';
const ADD_SIGNALED_USER = 'ADD_SIGNALED_USER';
const REMOVE_SIGNALED_USER = 'REMOVE_SIGNALED_USER';

const UPDATE_ANN_LIST = 'UPDATE_ANN_LIST';
const NEW_ANN = 'NEW_ANN';
const CREATE_ANN = 'CREATE_ANN';

module.exports = {
    USER_CONNECTED,
    USER_DISCONNECTED,
    JOIN_CHANNEL,
    UPDATE_USER_LIST,

    NEW_MESSAGE,
    CREATE_MESSAGE,

    UPDATE_CALL_LIST,
    NEW_CALL,
    CREATE_CALL,
    UPDATE_CALL,
    REMOVE_CALL,

    UPDATE_TOPIC_LIST,
    CREATE_TOPIC,
    ADD_TOPIC_VOTE,
    REMOVE_TOPIC_VOTE,
  
    UPDATE_SUBJECT,        
    SET_SUBJECT,

    UPDATE_SIGNALED_LIST,
    ADD_SIGNALED_USER,
    REMOVE_SIGNALED_USER,

    UPDATE_ANN_LIST,
    NEW_ANN,
    CREATE_ANN, 
};